language: python
python:
 - "3.6"
install:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install numpy
script:
#  - echo "run_tests"
# after_script:
  - cd doc
  - sphinx-apidoc -e -o . ../multilog/
  - mkdir _build; mkdir _build/html; echo "Hello World" > _build/html/index.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PAGES_TOKEN
  keep_history: true
  local_dir: doc/_build/html/
  on:
    branch: develop
  
